// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfidlqjklkjkkldrlqer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmaWRscWprbGtqa2tsZHJscWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzIyNjgsImV4cCI6MjA2NTg0ODI2OH0.qPbTc0gbR65qUv8APAGRhyR4dpOXC6h-dm3ruEtllro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);